name: Muffin store automation tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Run Tests
        run: npm run test

      - name: Upload Playwright report to artifactory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: playwright-report/
          retention-days: 1
